pipeline {
    agent any

    tools {
        maven 'Maven_3'  // Use the Maven tool installed in Jenkins (Configure this under Jenkins > Global Tool Configuration)
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Pradeepbaskar07/Robust-Automation-Framework.git'
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Archive Reports') {
            steps {
                archiveArtifacts artifacts: 'reports/**, screenshots/**', allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            junit 'target/surefire-reports/*.xml'
        }
    }
}

